//! Guards the places an IPC command must be declared to work in a packaged
//! build, and the profile split that keeps production hardened:
//!
//! 1. `src/command_registration.rs` - `tauri::generate_handler![...]`
//!    (runtime dispatch), invoked by `src/lib.rs`
//! 2. `build.rs` - `AppManifest::commands(&[...])` (permission generation;
//!    a command missing here has no `allow-*` permission to reference)
//! 3. `permissions/autogenerated/*.toml` - generated app permission profiles
//! 4. `capabilities/development.json` - broad local development/debug allowlist
//! 5. `capabilities/production.json` - hardened production allowlist
//! 6. `tauri.conf.json` - production capability selector
//!
//! Tauri v2 denies IPC by default, so a command present in (1) but absent
//! from (2), (3), or the selected capability profile compiles fine and then
//! fails at runtime with a silent "Bridge Offline". These tests fail the build
//! instead.

use oomu_lib::tool_security::{classify_system_action, CapabilityRiskTier, SystemActionClass};
use serde_json::Value;
use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::{Path, PathBuf};

#[derive(Debug, Clone)]
struct CapabilityProfile {
    identifier: String,
    path: PathBuf,
    permissions: BTreeSet<String>,
}

fn manifest_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn read(path: &Path) -> String {
    fs::read_to_string(path)
        .unwrap_or_else(|err| panic!("failed to read {}: {err}", path.display()))
}

/// Commands registered for runtime dispatch in `generate_handler![...]`.
fn handler_commands() -> BTreeSet<String> {
    let source = read(&manifest_dir().join("src/command_registration.rs"));
    let marker = "generate_handler![";
    let start = source
        .find(marker)
        .expect("generate_handler![ not found in src/command_registration.rs")
        + marker.len();
    let end = start
        + source[start..]
            .find(']')
            .expect("unterminated generate_handler! block in src/command_registration.rs");
    source[start..end]
        .split(',')
        .map(str::trim)
        .filter(|entry| !entry.is_empty())
        .map(|entry| {
            entry
                .rsplit("::")
                .next()
                .expect("rsplit always yields at least one segment")
                .trim()
                .to_string()
        })
        .collect()
}

/// Commands registered for permission generation in `build.rs`.
fn build_manifest_commands() -> BTreeSet<String> {
    let source = read(&manifest_dir().join("build.rs"));
    let marker = ".commands(&[";
    let start = source
        .find(marker)
        .expect(".commands(&[ not found in build.rs")
        + marker.len();
    let end = start
        + source[start..]
            .find(']')
            .expect("unterminated .commands(&[...]) block in build.rs");
    source[start..end]
        .split(',')
        .map(|entry| entry.trim().trim_matches('"').to_string())
        .filter(|entry| !entry.is_empty())
        .collect()
}

/// Commands with generated application permission profile TOMLs.
fn generated_permission_commands() -> BTreeSet<String> {
    let dir = manifest_dir().join("permissions/autogenerated");
    let mut commands = BTreeSet::new();
    for entry in
        fs::read_dir(&dir).unwrap_or_else(|err| panic!("failed to read {}: {err}", dir.display()))
    {
        let entry = entry.expect("failed to read autogenerated permission entry");
        let path = entry.path();
        if path.extension().and_then(|value| value.to_str()) != Some("toml") {
            continue;
        }
        let stem = path
            .file_stem()
            .and_then(|value| value.to_str())
            .unwrap_or_else(|| panic!("invalid permission filename {}", path.display()));
        commands.insert(stem.to_string());
    }
    commands
}

fn permission_identifier(entry: &Value) -> String {
    entry
        .as_str()
        .or_else(|| entry["identifier"].as_str())
        .expect("permission entry is neither a string nor an object with an identifier")
        .to_string()
}

fn capability_profile_from_value(path: &Path, capability: &Value) -> CapabilityProfile {
    let identifier = capability["identifier"]
        .as_str()
        .unwrap_or_else(|| panic!("{} capability has no identifier", path.display()))
        .to_string();
    let permissions = capability["permissions"]
        .as_array()
        .unwrap_or_else(|| panic!("{} capability has no permissions array", path.display()))
        .iter()
        .map(permission_identifier)
        .collect();

    CapabilityProfile {
        identifier,
        path: path.to_path_buf(),
        permissions,
    }
}

/// Capability profiles listed in `capabilities/*.json`.
///
/// Entries may be single capability objects, arrays, or named capability lists;
/// all three forms are valid capability syntax.
fn capability_profiles() -> BTreeMap<String, CapabilityProfile> {
    let dir = manifest_dir().join("capabilities");
    let mut paths = fs::read_dir(&dir)
        .unwrap_or_else(|err| panic!("failed to read {}: {err}", dir.display()))
        .map(|entry| {
            entry
                .expect("failed to read capability directory entry")
                .path()
        })
        .filter(|path| path.extension().and_then(|value| value.to_str()) == Some("json"))
        .collect::<Vec<_>>();
    paths.sort();

    let mut profiles = BTreeMap::new();
    for path in paths {
        let value: Value = serde_json::from_str(&read(&path))
            .unwrap_or_else(|err| panic!("{} is not valid JSON: {err}", path.display()));
        let entries: Vec<CapabilityProfile> = if let Some(items) = value.as_array() {
            items
                .iter()
                .map(|capability| capability_profile_from_value(&path, capability))
                .collect()
        } else if let Some(items) = value["capabilities"].as_array() {
            items
                .iter()
                .map(|capability| capability_profile_from_value(&path, capability))
                .collect()
        } else {
            vec![capability_profile_from_value(&path, &value)]
        };

        for profile in entries {
            let previous = profiles.insert(profile.identifier.clone(), profile);
            assert!(previous.is_none(), "duplicate capability identifier found");
        }
    }

    profiles
}

fn capability_profile(identifier: &str) -> CapabilityProfile {
    capability_profiles()
        .remove(identifier)
        .unwrap_or_else(|| panic!("capabilities/{identifier}.json profile not found"))
}

fn configured_capability_references() -> Vec<String> {
    let path = manifest_dir().join("tauri.conf.json");
    let config: Value =
        serde_json::from_str(&read(&path)).expect("tauri.conf.json is not valid JSON");
    config["app"]["security"]["capabilities"]
        .as_array()
        .unwrap_or_else(|| panic!("{} has no app.security.capabilities array", path.display()))
        .iter()
        .map(|entry| entry.as_str().unwrap_or("INLINE_CAPABILITY").to_string())
        .collect()
}

fn allow_identifier(command: &str) -> String {
    format!("allow-{}", command.replace('_', "-"))
}

fn command_from_app_permission(permission: &str) -> Option<String> {
    // Namespaced permissions (core:*, http:*, plugin:*) are not app commands.
    if permission.contains(':') {
        return None;
    }
    let command = permission
        .strip_prefix("allow-")
        .or_else(|| permission.strip_prefix("deny-"))?;
    Some(command.replace('-', "_"))
}

fn allowed_app_commands(profile: &CapabilityProfile) -> BTreeSet<String> {
    profile
        .permissions
        .iter()
        .filter_map(|permission| permission.strip_prefix("allow-"))
        .map(|command| command.replace('-', "_"))
        .collect()
}

fn denied_app_commands(profile: &CapabilityProfile) -> BTreeSet<String> {
    profile
        .permissions
        .iter()
        .filter_map(|permission| permission.strip_prefix("deny-"))
        .map(|command| command.replace('-', "_"))
        .collect()
}

fn format_set(set: &BTreeSet<String>) -> String {
    set.iter().cloned().collect::<Vec<_>>().join("\n  ")
}

fn production_restricted_commands() -> BTreeSet<String> {
    [
        "apply_surgical_patch_directive",
        "audit_ark_artifacts",
        "delegate_signing_authority",
        "execute_connector_operation",
        "export_volatile_persistence",
        "generate_node_identity",
        "get_system_diagnostic_context",
        "recycle_autonomic_helper",
        "run_memory_comparative_audit",
        "run_pre_alpha_audit",
        "restore_persistence_migration_backup",
        "update_agent_configuration",
    ]
    .into_iter()
    .map(String::from)
    .collect()
}

#[test]
fn every_handler_command_is_registered_in_build_manifest() {
    let handler = handler_commands();
    let manifest = build_manifest_commands();
    assert!(
        !handler.is_empty(),
        "no commands parsed from generate_handler!"
    );

    let missing: BTreeSet<String> = handler.difference(&manifest).cloned().collect();
    assert!(
        missing.is_empty(),
        "commands in generate_handler! but missing from AppManifest::commands in build.rs \
         (no allow-* permission is generated for them):\n  {}",
        format_set(&missing),
    );
}

#[test]
fn build_manifest_has_no_stale_commands() {
    let handler = handler_commands();
    let manifest = build_manifest_commands();

    let stale: BTreeSet<String> = manifest.difference(&handler).cloned().collect();
    assert!(
        stale.is_empty(),
        "commands in build.rs AppManifest::commands but absent from generate_handler! \
         (stale registration or typo):\n  {}",
        format_set(&stale),
    );
}

#[test]
fn registered_commands_have_generated_permission_profiles() {
    let manifest = build_manifest_commands();
    let generated = generated_permission_commands();

    let missing: BTreeSet<String> = manifest.difference(&generated).cloned().collect();
    assert!(
        missing.is_empty(),
        "commands in build.rs AppManifest::commands but missing generated permission TOMLs:\n  {}",
        format_set(&missing),
    );

    let stale: BTreeSet<String> = generated.difference(&manifest).cloned().collect();
    assert!(
        stale.is_empty(),
        "generated permission TOMLs with no matching command in build.rs AppManifest::commands \
         (stale generated profile or typo):\n  {}",
        format_set(&stale),
    );
}

#[test]
fn tauri_config_selects_only_hardened_production_capability() {
    let configured = configured_capability_references();
    assert_eq!(
        configured,
        vec!["production".to_string()],
        "tauri.conf.json must explicitly select only the hardened production capability; \
         otherwise every file in src-tauri/capabilities is enabled by default"
    );
}

#[test]
fn development_capability_allows_every_handler_command() {
    let handler = handler_commands();
    let development = capability_profile("development");
    let permissions = &development.permissions;

    let missing: BTreeSet<String> = handler
        .iter()
        .filter(|command| !permissions.contains(&allow_identifier(command)))
        .cloned()
        .collect();
    assert!(
        missing.is_empty(),
        "commands in generate_handler! with no active allow-* entry in \
         {}:\n  {}",
        development.path.display(),
        format_set(&missing),
    );

    let denied = denied_app_commands(&development);
    assert!(
        denied.is_empty(),
        "commands explicitly denied in {} (deny-* overrides allow-*):\n  {}",
        development.path.display(),
        format_set(&denied),
    );
}

#[test]
fn production_capability_matches_hardened_command_set() {
    let handler = handler_commands();
    let restricted = production_restricted_commands();
    let production = capability_profile("production");
    let allowed = allowed_app_commands(&production);
    let denied = denied_app_commands(&production);

    let unknown_restricted: BTreeSet<String> = restricted.difference(&handler).cloned().collect();
    assert!(
        unknown_restricted.is_empty(),
        "production restricted command list contains commands absent from generate_handler!:\n  {}",
        format_set(&unknown_restricted),
    );

    let expected: BTreeSet<String> = handler.difference(&restricted).cloned().collect();
    let missing: BTreeSet<String> = expected.difference(&allowed).cloned().collect();
    assert!(
        missing.is_empty(),
        "production capability is missing required production command permissions:\n  {}",
        format_set(&missing),
    );

    let extra: BTreeSet<String> = allowed.difference(&expected).cloned().collect();
    assert!(
        extra.is_empty(),
        "production capability allows debug-only or intentionally restricted commands:\n  {}",
        format_set(&extra),
    );

    assert!(
        denied.is_empty(),
        "production capability should remove restricted commands instead of relying on deny-* entries:\n  {}",
        format_set(&denied),
    );
}

#[test]
fn default_capability_matches_hardened_production_profile() {
    let default_profile = capability_profile("default");
    let production = capability_profile("production");
    assert_eq!(
        default_profile.permissions, production.permissions,
        "default capability must remain a compatibility alias for the hardened production profile"
    );
}

#[test]
fn remote_mcp_cancellation_is_enabled_in_every_runtime_profile() {
    let command = "mcp_cancel_remote_operations";
    assert!(handler_commands().contains(command));
    assert!(build_manifest_commands().contains(command));
    assert!(generated_permission_commands().contains(command));

    let permission = allow_identifier(command);
    for identifier in ["default", "development", "production"] {
        let profile = capability_profile(identifier);
        assert!(
            profile.permissions.contains(&permission),
            "{} must allow remote MCP cancellation so Stop and route teardown work in packaged builds",
            profile.path.display()
        );
    }
}

#[test]
fn restricted_production_commands_remain_available_in_development_profile() {
    let development = capability_profile("development");
    let missing: BTreeSet<String> = production_restricted_commands()
        .iter()
        .filter(|command| !development.permissions.contains(&allow_identifier(command)))
        .cloned()
        .collect();
    assert!(
        missing.is_empty(),
        "development capability should retain debug/restricted commands for explicit local diagnostics:\n  {}",
        format_set(&missing),
    );
}

#[test]
fn raw_connector_execution_is_development_only() {
    let permission = allow_identifier("execute_connector_operation");
    assert!(capability_profile("development")
        .permissions
        .contains(&permission));
    for profile in [
        capability_profile("default"),
        capability_profile("production"),
    ] {
        assert!(
            !profile.permissions.contains(&permission),
            "{} must route connector execution through the Task-bound runtime",
            profile.path.display()
        );
    }
}

#[test]
fn capabilities_have_no_stale_app_permissions() {
    let handler = handler_commands();
    let generated = generated_permission_commands();
    let mut stale = BTreeSet::new();
    let mut missing_generated_profile = BTreeSet::new();

    for profile in capability_profiles().values() {
        for permission in &profile.permissions {
            let Some(command) = command_from_app_permission(permission) else {
                continue;
            };
            let entry = format!("{}: {}", profile.path.display(), permission);
            if !handler.contains(&command) {
                stale.insert(entry.clone());
            }
            if !generated.contains(&command) {
                missing_generated_profile.insert(entry);
            }
        }
    }

    assert!(
        stale.is_empty(),
        "app-command permissions in capabilities/*.json that match no command in \
         generate_handler! (stale entry or typo; they allow nothing):\n  {}",
        format_set(&stale),
    );
    assert!(
        missing_generated_profile.is_empty(),
        "app-command permissions in capabilities/*.json with no generated permission TOML:\n  {}",
        format_set(&missing_generated_profile),
    );
}

#[test]
fn shield_native_decision_has_no_renderer_resolver_surface() {
    let retired = "resolve_shield_approval";
    assert!(
        !handler_commands().contains(retired),
        "the renderer must not be able to dispatch a Shield decision"
    );
    assert!(
        !build_manifest_commands().contains(retired),
        "the retired Shield resolver must not receive a generated permission"
    );
    assert!(
        !generated_permission_commands().contains(retired),
        "the retired Shield resolver permission file must not exist"
    );
    for profile in capability_profiles().values() {
        assert!(
            !profile.permissions.contains(&allow_identifier(retired)),
            "{} must not expose renderer Shield resolution",
            profile.path.display()
        );
    }
}

#[test]
fn system_action_policy_routes_unapproved_capabilities_to_permission_pause() {
    let runtime_source = read(&manifest_dir().join("src/workflow_runtime.rs"));
    let system_action_source = read(&manifest_dir().join("src/workflow_runtime/system_action.rs"));
    assert!(
        runtime_source.contains("mod system_action;")
            && runtime_source.contains("execute_system_action_node("),
        "workflow execution must continue to delegate system actions to the policy module"
    );
    assert!(
        system_action_source.contains("classify_system_action(")
            && system_action_source.contains("classification.requires_human_approval()")
            && system_action_source.contains("pause_for_external_action("),
        "unsafe system actions must continue to use classifier-backed interactive approval pauses"
    );

    let read_only =
        classify_system_action(SystemActionClass::Binary, "git", &["status".to_string()]);
    assert_eq!(read_only.tier, CapabilityRiskTier::ReadOnly);
    assert!(
        !read_only.requires_human_approval(),
        "read-only system diagnostics should not require a permission pause"
    );

    let file_read = classify_system_action(SystemActionClass::Binary, "cat", &["notes.txt".into()]);
    assert_eq!(file_read.tier, CapabilityRiskTier::FileRead);
    assert!(
        !file_read.requires_human_approval(),
        "read-only filesystem tools should not require a permission pause"
    );

    let file_write = classify_system_action(SystemActionClass::Binary, "rm", &["-rf".to_string()]);
    assert_eq!(file_write.tier, CapabilityRiskTier::FileWrite);
    assert!(
        file_write.requires_human_approval(),
        "modifying write commands must require explicit human approval"
    );

    let system_exec = classify_system_action(SystemActionClass::Shell, "echo ok && rm -rf /", &[]);
    assert_eq!(system_exec.tier, CapabilityRiskTier::SystemExec);
    assert!(
        system_exec.requires_human_approval(),
        "shell control syntax must require explicit human approval"
    );
}
