import { describe,expect,it } from "vitest";
import { validateGoldenTaskMatrix,validateHeroWorkflow,validatePrivacyDeclarations,validateRecoveryMatrix } from "../p0-release-acceptance.mjs";

const expected={buildIdentifier:"build-232",sourceRevision:"a".repeat(40),artifactDigest:`sha256:${"b".repeat(64)}`};
const bound={schemaVersion:1,...expected};
describe("P0 executed release acceptance",()=>{
  it("requires eight unattended golden completions and unique confirmed effects",()=>{const runs=Array.from({length:10},(_,index)=>({id:`p0-${index}`,executed:true,terminalState:index<8?"completed":"failed",evidence:[{}],errorCode:index<8?null:"expected_failure",accurateTerminalState:true,confirmedEffects:index===0?[{idempotencyKey:"effect-1",verifiedPostcondition:true}]:[]}));expect(validateGoldenTaskMatrix({...bound,runs},expected).status).toBe("passed");runs[1].confirmedEffects=[{idempotencyKey:"effect-1",verifiedPostcondition:true}];expect(validateGoldenTaskMatrix({...bound,runs},expected).failures.join(" ")).toMatch(/duplicated/);});
  it("requires every recovery scenario without duplicated effects",()=>{const ids=["restart","sleep_wake","lost_network","revoked_permissions","expired_credentials","denied_approval","model_failure_fallback","corrupted_artifact","channel_delivery_failure"];const record={...bound,scenarios:ids.map((id)=>({id,executed:true,terminalState:"completed",evidenceArchived:true,duplicateConfirmedEffects:0}))};expect(validateRecoveryMatrix(record,expected).status).toBe("passed");record.scenarios[0].duplicateConfirmedEffects=1;expect(validateRecoveryMatrix(record,expected).status).toBe("failed");});
  it("requires all hero modes, verified artifacts, clean Mac timing, and declarations",()=>{const artifact={docxStructurallyVerified:true,pdfVisuallyVerified:true,signedManifestVerified:true};const record={...bound,runs:["on_demand","routine","restart","authorized_channel"].map((mode)=>({mode,executed:true,terminalState:"completed",taskEvidenceArchived:true,sourceLinksVerified:true,artifact})),cleanMac:{installedSignedNotarizedBuild:true,developerToolingUsed:false,timeToUsefulOutputMs:599000}};expect(validateHeroWorkflow(record,expected).status).toBe("passed");record.cleanMac.timeToUsefulOutputMs=600001;expect(validateHeroWorkflow(record,expected).status).toBe("failed");expect(validatePrivacyDeclarations({...bound,backgroundHelperDisclosureMatches:true,networkBehaviorMatches:true,privacyCopyMatches:true,entitlementsMatch:true,appStoreDeclarationsMatch:true},expected).status).toBe("passed");});
});
