import { existsSync, readFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { describe, expect, it } from "vitest";
import {
  assertNativeCommandHandlerWiring,
  registeredProductionCommands,
} from "../native-command-registry.mjs";
import {
  SUPPORTED_LOCALE_FILES,
  validateConfiguredLocaleResources,
} from "../release-gates/bundle-resource-inventory.mjs";

const root = resolve(import.meta.dirname, "..", "..");

function read(relativePath) {
  return readFileSync(join(root, relativePath), "utf8");
}

function commandSet(source, marker) {
  const start = source.indexOf(marker);
  expect(start, `${marker} must exist`).toBeGreaterThanOrEqual(0);
  const bodyStart = start + marker.length;
  const bodyEnd = source.indexOf("]", bodyStart);
  expect(bodyEnd, `${marker} must have a closing bracket`).toBeGreaterThan(bodyStart);
  return new Set(
    source
      .slice(bodyStart, bodyEnd)
      .split(",")
      .map((value) => value.trim().replace(/^"|"$/g, ""))
      .filter(Boolean)
      .map((value) => value.split("::").at(-1)),
  );
}

const scenarioDesktopCommands = [
  "create_routine",
  "get_routine_history",
  "get_task_run",
  "get_workflow_capability_catalog",
  "get_workflows",
  "grant_routine_authority",
  "list_routines",
  "list_task_runs",
  "propose_routine",
  "reconcile_task_runs",
  "reserve_task_effect",
  "resolve_task_effect_verification",
  "resolve_workflow_permission",
  "resume_task_run",
  "retry_routine_delivery",
  "retry_task_run",
  "run_routine_now",
  "save_workflow",
  "verify_task_effect",
];

describe("packaged consolidated-scenario task tools", () => {
  it("registers every native Task tool on the production startup path", () => {
    const startup = read("src-tauri/src/lib.rs");
    const productionRegistry = read("src-tauri/src/production_task_tools.rs");
    const systemRegistry = read("src-tauri/src/tools/mod.rs");

    const registration = "production_task_tools::register_production_task_tools()?;";
    expect(startup).toContain(registration);
    expect(startup.indexOf(registration)).toBeLessThan(startup.indexOf("tauri::Builder::default()"));
    expect(productionRegistry).toContain("artifacts::register_file_task_tool()");
    expect(productionRegistry).toContain("tools::register_system_task_tools()");

    const registrations = [
      ["official_page", "fetch_official_page"],
      ["project_file", "read_project_file"],
      ["milestone_analysis", "analyze_project_milestones"],
      ["supplier_exception", "analyze_supplier_exceptions"],
      ["evidence_report_validation", "validate_evidence_report"],
      ["system_calendar_event", "create_conflict_free_calendar_event"],
      ["system_mail_send", "send_system_email"],
      ["evidence_artifacts", "prepare_background_agent_comparison"],
      ["evidence_artifacts", "prepare_milestone_constraint_recovery_plan"],
    ];
    for (const [moduleName, operation] of registrations) {
      expect(systemRegistry).toContain(`mod ${moduleName};`);
      expect(systemRegistry).toMatch(
        new RegExp(`${moduleName}::register_task_tool(?:s)?\\(\\)(?:\\?)?;?`),
      );
      const implementation = read(`src-tauri/src/tools/${moduleName}.rs`);
      expect(implementation).toContain(operation);
      expect(implementation).toContain("TaskToolRegistration");
    }
    expect(read("src-tauri/src/artifacts/agent_tool.rs")).toContain(
      'operation: "create_file"',
    );
  });

  it("keeps every renderer-facing command reachable in packaged profiles", () => {
    expect(() => assertNativeCommandHandlerWiring(root)).not.toThrow();
    const handler = registeredProductionCommands(root);
    const buildManifest = commandSet(read("src-tauri/build.rs"), ".commands(&[");

    for (const command of scenarioDesktopCommands) {
      expect(handler, `${command} runtime handler`).toContain(command);
      expect(buildManifest, `${command} build manifest`).toContain(command);

      const permissionPath = join(
        root,
        "src-tauri",
        "permissions",
        "autogenerated",
        `${command}.toml`,
      );
      expect(existsSync(permissionPath), `${command} generated permission`).toBe(true);
      const permission = readFileSync(permissionPath, "utf8");
      expect(permission).toContain(`commands.allow = ["${command}"]`);

      const identifier = `allow-${command.replaceAll("_", "-")}`;
      for (const profile of ["default", "development", "production"]) {
        const capability = JSON.parse(read(`src-tauri/capabilities/${profile}.json`));
        expect(capability.permissions, `${identifier} in ${profile}`).toContain(identifier);
      }
    }
  });

  it("packages the native artifact and trusted Mail dependencies used at execution time", () => {
    const baseConfig = JSON.parse(read("src-tauri/tauri.conf.json"));
    const releaseConfig = JSON.parse(read("src-tauri/tauri.release.conf.json"));
    const requiredArtifactHelpers = [
      "binaries/artifact_build_helper",
      "binaries/oomu-artifact-pdf-helper",
    ];
    for (const helper of requiredArtifactHelpers) {
      expect(baseConfig.bundle.externalBin).toContain(helper);
      expect(releaseConfig.bundle.externalBin).toContain(helper);
    }

    expect(baseConfig.bundle.resources).toContain("resources/mcp/mcp_applescript.py");
    expect(validateConfiguredLocaleResources(baseConfig)).toEqual(
      SUPPORTED_LOCALE_FILES.map((file) => `../src/locales/${file}`).sort(),
    );
    const mailBridge = read("src-tauri/resources/mcp/mcp_applescript.py");
    expect(mailBridge).toContain('"name": "send_system_email"');
    expect(mailBridge).toContain("return send_system_email(arguments)");
    const nativeMailSend = read("src-tauri/src/tools/system_mail_send.rs");
    expect(nativeMailSend).toContain("TaskToolApprovalTier::Explicit");
    expect(nativeMailSend).toContain("TaskToolRiskTier::SystemExec");
    expect(nativeMailSend).toContain(".send_mail(local_mail_send_request(&request))");

    expect(read("src-tauri/Cargo.toml")).toContain("objc2-event-kit");
    expect(read("src-tauri/Info.plist")).toContain("NSCalendarsFullAccessUsageDescription");
    expect(read("src-tauri/Info.plist")).toContain("NSAppleEventsUsageDescription");
    expect(read("src-tauri/entitlements.plist")).toContain(
      "com.apple.security.automation.apple-events",
    );
    expect(read("src-tauri/entitlements.plist")).toContain(
      "com.apple.security.personal-information.calendars",
    );
    expect(read("src-tauri/entitlements.plist")).toContain(
      "com.apple.security.personal-information.addressbook",
    );
  });
});
