import { existsSync, readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

function filesWithExtension(relativeDirectory: string, extension: string) {
  return readdirSync(join(process.cwd(), relativeDirectory), { withFileTypes: true })
    .filter((entry) => entry.isFile() && entry.name.endsWith(extension))
    .map((entry) => join(relativeDirectory, entry.name));
}

function shippedSourceFiles(relativeDirectory: string): string[] {
  return readdirSync(join(process.cwd(), relativeDirectory), { withFileTypes: true }).flatMap(
    (entry) => {
      const relativePath = join(relativeDirectory, entry.name);
      if (entry.isDirectory()) {
        if (entry.name === "__tests__" || entry.name === "tests") {
          return [];
        }
        return shippedSourceFiles(relativePath);
      }
      return /\.(?:rs|ts|tsx)$/u.test(entry.name) && !/\.test\.[^.]+$/u.test(entry.name)
        ? [relativePath]
        : [];
    },
  );
}

const productionFiles = [...new Set([
  ...shippedSourceFiles("src/app"),
  ...shippedSourceFiles("src/lib"),
  ...shippedSourceFiles("src-tauri/src"),
  "src-tauri/build.rs",
  "src-tauri/capabilities/default.json",
  "src-tauri/capabilities/development.json",
  "src-tauri/capabilities/production.json",
  "src-tauri/gen/schemas/desktop-schema.json",
  "src-tauri/gen/schemas/macOS-schema.json",
  "src-tauri/gen/schemas/acl-manifests.json",
  "src-tauri/gen/schemas/capabilities.json",
  ...filesWithExtension("src-tauri/permissions/autogenerated", ".toml"),
])].filter((relativePath) => existsSync(join(process.cwd(), relativePath)));

const forbiddenProductionSignatures = [
  "project_milestones.json",
  "calendar_draft.md",
  "supplier_proposals.json",
  "supplier_audit_matrix.md",
  "claim_appeal_es.md",
  "apex_health_denial_example_user.pdf",
  "wednesday, july 8, 2026",
  "mobile documents/com~apple~clouddocs/oomu test data",
  "run_supplier_reconciliation_audit",
  "resolve_icloud_planning_testing",
  "icloud_planning_testing_roots",
  "resolve_oomu_testing_dir",
  "eldris oomu.app",
  'normalized.includes("/claim")',
  "taskflowdemorole",
  "directory_summarizer_input",
  "directory_summarizer_report.md",
  "ensure_directory_summarizer_seed",
  "ensure_mcp_sandbox_seed_files",
  "mcp_sandbox_instruction_input",
  "mcp_sandbox_data_source",
  "taskflow demo workspace",
  "fn write_ark_deliverable(",
  "fn should_write_ark_deliverable(",
  "fn write_ark_for_plan(",
  "action_plan_direct_export",
  "opened markdown report in textedit",
  "pub simulate_failure",
  "spawn_agentic_consultation",
  "run_oomu_boardroom_actor",
  "run_oomu_boardroom_actor",
  "combined directive: oomu's serialized proposal",
  "i reviewed only oomu's serialized proposal payload",
] as const;

function shippedSource(relativePath: string) {
  const source = readFileSync(join(process.cwd(), relativePath), "utf8");
  if (!relativePath.endsWith(".rs")) {
    return source;
  }
  return source.split(/\n#\[cfg\(test\)\]\nmod tests\s*\{/u, 1)[0];
}

describe("production acceptance data boundary", () => {
  it("removes the fixture-only supplier command permission", () => {
    expect(
      existsSync(
        join(
          process.cwd(),
          "src-tauri/permissions/autogenerated/run_supplier_reconciliation_audit.toml",
        ),
      ),
    ).toBe(false);
  });

  it.each(productionFiles)("keeps audited constants out of %s", (relativePath) => {
    const source = shippedSource(relativePath).toLowerCase();
    for (const signature of forbiddenProductionSignatures) {
      expect(source, `${relativePath} contains ${signature}`).not.toContain(
        signature.toLowerCase(),
      );
    }
  });
});
